# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad923e970f493a52fe866aa230e68b7d0549ed9dbf387711e2f05d7750224cf464ad466239e5487c43c7f40c677122ccd5ab2cd95439d4cb7b61d05876698c4d

test:
  secret_key_base: 933088b8f17d59920d8949fc97398d584561eb6b3cfd68d38cc924d5c70994366a642b16a6d61322a2e681e33d016a1d5204bb357dc1acfd87d82ba16d9b14b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
